# Generated by Django 2.1.7 on 2020-06-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='이메일'),
        ),
    ]
